#!/usr/bin/env python

# Copyright (C) 2018  Statoil ASA, Norway.
#
# Moclipse is part of Ert, Ensemble Reservoir Tools.
#
# Ert is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# Moclipse is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.
#
# See the GNU General Public License at <http://www.gnu.org/licenses/gpl.html>
# for more details.

from __future__ import (division, print_function)

import os.path


from summary import generate_summary
from parser import parse
from luna_util import log








def main(eclbase):
    state = parse(eclbase)

    smry = generate_summary(state)
    smry.fwrite()
    print('Simulation complete.  Wrote {}.'.format(', '.join(smry.keys())))


if __name__ == '__main__':
    from sys import argv
    if len(argv) != 2:
        exit('Usage: moclipse ECL')

    eclbase = argv[1]
    if not os.path.exists(eclbase + '.DATA'):
        exit('No such file {} (.DATA)'.format(eclbase))

    main(eclbase=eclbase, )
